services:
  api:
    build: .
    container_name: ${WORKSPACE}-api
    labels:
      app: ${WORKSPACE}
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    volumes:
      - .:/app
    environment:
      - POSTGRES_HOST=postgres
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    env_file: .env
    restart: always

networks:
  default:
    name: ${WORKSPACE}-network
